name: Work 3 Fabian Python
on: [push]
jobs:
  build-python:
    runs-on: ubuntu-latest
    container: python:3.12
    steps:
      - run: echo "TESTING PYTHON"
      - run: python --version
      - run: pip --version
      - uses: actions/checkout@v3
      - run: python -m py_compile app.py
      - run: python app.py
